### ISSUE TITLE
Invalid Control Block reference upon opening SCD file

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-supervision#3]
Using https://danyill.github.io/oscd-supervision/index.deploy.html at 18afca929ef4a6940c2276999d27fafb528eeb94

Google Chrome Version: `117.0.5938.132 (Official Build) (64-bit)`

There is some unusual behaviour for the attached SCD file when it is first opened.

[2023-10-01_prot2_base_configuration_XAT.zip](https://github.com/danyill/oscd-supervision/files/12776654/2023-10-01_prot2_base_configuration_XAT.zip)

For the first IED in the file, it gives an error `Invalid Control Block reference "XAT_T2_P2LVCB/LLN0.Ctl_2`. Clicking the Info button does not do anything (maybe not yet implemented?).

However, when I open the select IED button, then close it, the error goes away and I can see that the LGOS is indeed used.

https://github.com/danyill/oscd-supervision/assets/3224671/015a00ad-8c0c-4f88-a7c2-008bcba9fc21

Perhaps there is something going wrong when the SCD file is opened?

## Digging into oscd-supervision.ts...

It appears that `this.allControlBlockIds` is an empty array when the very first LGOS is parsed.

Maybe we need to run `this.updateControlBlockInfo()` after opening an SCD file?

**Comment by danyill** [comment]
You are quite correct. Thank you for this feedback.

**Comment by danyill** [comment]
The Info button is really just there to show a tooltip to say that the first instance can't be deleted.

It's a slightly klunky way to show this I guess.

![image](https://github.com/danyill/oscd-supervision/assets/674783/4b4cde25-56ed-420b-9d22-78ca8bdc741e)

I don't really have a better idea, although I've made the icon a bit more relevant:

![image](https://github.com/danyill/oscd-supervision/assets/674783/aa2189ed-0f1a-4b35-a0f6-a7b8ea621c1a)

If you have a suggestion to improve, please open an issue for it.
