### ISSUE TITLE
Connection between supervision and control block out of order

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-supervision#4]
(@danyill masquerading to describe issue @jarradraumati found)

Generally, supervisions go in the correct order but I found a case where they do not:

![image](https://github.com/danyill/oscd-supervision/assets/3224671/4ef43e4c-4f8c-4622-a0b2-c5dcc8547675)

Here is a video:

https://github.com/danyill/oscd-supervision/assets/3224671/c43e88ab-4734-4501-b4f9-bdbbc29f7f56

Here is the scd file:

[XAT (13).zip](https://github.com/danyill/oscd-supervision/files/13329218/XAT.13.zip)

The issue seems only be the UI because the intended connections is shown for the `Val` of the `setSrcRef`:

```xml
<LN desc="HV_MU_Trips" lnType="SIEMENS_6MU85_01SIPROTEC5_LNType_LGOS" prefix="HV_" lnClass="LGOS" inst="2">
	<Private type="Siemens-MasterId">d797cd79-1a63-4498-9af5-878a2baa3066</Private>
	<DOI desc="Mode (controllable)" name="Mod">
		<SDI name="Oper"/>
	</DOI>
	<DOI desc="Behavior" name="Beh"/>
	<DOI desc="Health" name="Health"/>
	<DOI desc="Name plate" name="NamPlt">
		<DAI name="configRev">
			<Val>2023-06-08 09:06:31</Val>
		</DAI>
	</DOI>
	<DOI desc="Needs commissioning" name="NdsCom"/>
	<DOI desc="Status subscription" name="St"/>
	<DOI desc="Status Sim messages" name="SimSt"/>
	<DOI desc="Exp. conf. rev." name="ConfRevNum"/>
	<DOI desc="Rec. conf. rev." name="RxConfRevNum"/>
	<DOI desc="Ref. GOOSE CB" name="GoCBRef">
		<DAI name="setSrcRef" valImport="true">
			<Val>XAT_242_M2Prot_MechanicalTrips/LLN0.Ctl_1</Val>
		</DAI>
	</DOI>
	<DOI desc="Diagnosis error" name="DiagErr"/>
</LN>
```

**Comment by danyill** [comment]
Thank you for filing this issue -- it is most helpful.

Just one of the render functions had not consistently used the helper function to generate the supervisions and that appears to be the cause of this. PR on the way.
